import { collection, getDocs, writeBatch, doc } from 'firebase/firestore';
import { db } from '../firebase';
import { Product } from './types';
import { handleFirestoreError, OperationType } from './api';

const INITIAL_PRODUCTS = [
  { name:"Crowned In Blood", sku:"9781958769225", category:"Paperback", basePrice:25.99, productionCost:6.28, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:36.99, freeShipping:0, bookStock:21, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:21, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:2, csvAvgDaily:0.02, csvReorderThreshold:0, leadTime:14, booksInBundle:"", bundles:"Spicy Standalone Bundle" },
  { name:"Crowned In Blood - Art Pack", sku:"CrownedInBloodArtPack", category:"Art Pack", basePrice:19.99, productionCost:2.23, shippingCost:0.30, shippingSuppliesCost:0.84, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:23.99, freeShipping:0, bookStock:9, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:5, bookInventory:4, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.37, csvReorderThreshold:3, leadTime:7, booksInBundle:"", bundles:"Crowned In Blood Book Box,Crowned In Blood Book Box - S&D,Crowned In Blood Foiled Paperback,Crowned In Blood Foiled Paperback - S&D,The Complete Dark Romance Paperback Collection,The Complete Dark Romance Paperback Collection - S&D" },
  { name:"Crowned In Blood - S&D", sku:"CrownedInBloodS&D", category:"Paperback", basePrice:23.99, productionCost:6.28, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:32.99, freeShipping:0, bookStock:1, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:1, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:1, csvAvgDaily:0.02, csvReorderThreshold:0, leadTime:14, booksInBundle:"", bundles:"Spicy Standalone Bundle - S&D" },
  { name:"Crowned In Blood Book Box", sku:"CrownedInBloodDEBB", category:"Book Box", basePrice:104.99, productionCost:9.77, shippingCost:3.14, shippingSuppliesCost:4.73, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:109.99, freeShipping:6.50, bookStock:0, booksPurchased:0, bundlesPurchased:5, purchasedViaBundles:0, bookInventory:0, bundlesInventory:4, sixMonthBookSales:0, sixMonthBundleSales:29, csvAvgDaily:0.19, csvReorderThreshold:0, leadTime:60, booksInBundle:"Crowned In Blood Deluxe Edition,Crowned In Blood - Art Pack", bundles:"" },
  { name:"Crowned In Blood Book Box - S&D", sku:"CrownedInBloodDEBB-S&D", category:"Book Box", basePrice:94.99, productionCost:9.77, shippingCost:3.14, shippingSuppliesCost:4.73, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:99.99, freeShipping:6.50, bookStock:0, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:0, bundlesInventory:4, sixMonthBookSales:0, sixMonthBundleSales:1, csvAvgDaily:0.01, csvReorderThreshold:0, leadTime:60, booksInBundle:"Crowned In Blood Deluxe Edition - S&D,Crowned In Blood - Art Pack", bundles:"" },
  { name:"Crowned In Blood Deluxe Edition", sku:"CrownedInBloodDEHC", category:"Hardcover", basePrice:94.99, productionCost:7.54, shippingCost:2.84, shippingSuppliesCost:4.26, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:94.99, freeShipping:6.50, bookStock:195, booksPurchased:5, bundlesPurchased:0, purchasedViaBundles:5, bookInventory:185, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.22, csvReorderThreshold:13, leadTime:60, booksInBundle:"", bundles:"Crowned In Blood Book Box" },
  { name:"Crowned In Blood Deluxe Edition - S&D", sku:"CrownedInBloodDEHC-S&D", category:"Hardcover", basePrice:79.99, productionCost:7.54, shippingCost:2.84, shippingSuppliesCost:4.26, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:79.99, freeShipping:6.50, bookStock:55, booksPurchased:7, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:48, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.04, csvReorderThreshold:3, leadTime:60, booksInBundle:"", bundles:"Crowned In Blood Book Box - S&D" },
  { name:"Crowned In Blood Foiled Paperback", sku:"9781958769232", category:"Paperback", basePrice:44.99, productionCost:11.07, shippingCost:2.77, shippingSuppliesCost:4.71, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:43.99, freeShipping:0, bookStock:11, booksPurchased:1, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:10, bundlesInventory:4, sixMonthBookSales:20, sixMonthBundleSales:0, csvAvgDaily:0.28, csvReorderThreshold:7, leadTime:25, booksInBundle:"Crowned In Blood Foiled Paperback,Crowned In Blood - Art Pack", bundles:"The Complete Dark Romance Paperback Collection" },
  { name:"Crowned In Blood Foiled Paperback - S&D", sku:"CrownedInBloodFoiledPBS&D", category:"Paperback", basePrice:41.99, productionCost:11.07, shippingCost:2.77, shippingSuppliesCost:4.71, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:39.99, freeShipping:0, bookStock:5, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:5, bundlesInventory:4, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.02, csvReorderThreshold:0, leadTime:25, booksInBundle:"Crowned In Blood Foiled Paperback - S&D,Crowned In Blood - Art Pack", bundles:"The Complete Dark Romance Paperback Collection - S&D" },
  { name:"Immortal Book Boyfriends Paperback Bundle", sku:"9602009000022", category:"Bundle", basePrice:63.99, productionCost:18.25, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:89.99, freeShipping:7.00, bookStock:0, booksPurchased:0, bundlesPurchased:6, purchasedViaBundles:0, bookInventory:0, bundlesInventory:7, sixMonthBookSales:0, sixMonthBundleSales:86, csvAvgDaily:0.51, csvReorderThreshold:0, leadTime:14, booksInBundle:"Night Shade,Night Fury,Night Fall,My Brutal Beast", bundles:"" },
  { name:"Immortal Book Boyfriends Paperback Bundle - S&D", sku:"ImmortalBookBoyfriendsS&D", category:"Bundle", basePrice:48.99, productionCost:18.25, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:82.99, freeShipping:7.00, bookStock:0, booksPurchased:0, bundlesPurchased:1, purchasedViaBundles:0, bookInventory:0, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:1, csvAvgDaily:0.01, csvReorderThreshold:0, leadTime:14, booksInBundle:"Night Shade - S&D,Night Fury - S&D,Night Fall - S&D,My Brutal Beast - S&D", bundles:"" },
  { name:"My Brutal Beast", sku:"9781958769096", category:"Paperback", basePrice:19.99, productionCost:2.55, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:28.99, freeShipping:0, bookStock:15, booksPurchased:1, bundlesPurchased:0, purchasedViaBundles:6, bookInventory:8, bundlesInventory:0, sixMonthBookSales:14, sixMonthBundleSales:0, csvAvgDaily:0.76, csvReorderThreshold:11, leadTime:14, booksInBundle:"", bundles:"Immortal Book Boyfriends Paperback Bundle,The Complete Dark Romance Paperback Collection,Spicy Standalone Bundle" },
  { name:"My Brutal Beast - S&D", sku:"MyBrutalBeastS&D", category:"Paperback", basePrice:17.99, productionCost:2.55, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:26.99, freeShipping:0, bookStock:1, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:1, bookInventory:0, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.04, csvReorderThreshold:1, leadTime:14, booksInBundle:"", bundles:"Immortal Book Boyfriends Paperback Bundle - S&D,The Complete Dark Romance Paperback Collection - S&D,Spicy Standalone Bundle - S&D" },
  { name:"Night Fall", sku:"9781958769003", category:"Paperback", basePrice:24.99, productionCost:5.88, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:36.99, freeShipping:0, bookStock:18, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:6, bookInventory:12, bundlesInventory:0, sixMonthBookSales:7, sixMonthBundleSales:0, csvAvgDaily:0.74, csvReorderThreshold:10, leadTime:14, booksInBundle:"", bundles:"The Vampire War Paperback Bundle: Books 1-3,Immortal Book Boyfriends Paperback Bundle,The Complete Dark Romance Paperback Collection" },
  { name:"Night Fall - S&D", sku:"NightFallS&D", category:"Paperback", basePrice:22.99, productionCost:5.88, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:33.99, freeShipping:0, bookStock:16, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:1, bookInventory:15, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.03, csvReorderThreshold:0, leadTime:14, booksInBundle:"", bundles:"The Vampire War Paperback Bundle: Books 1-3 - S&D,Immortal Book Boyfriends Paperback Bundle - S&D,The Complete Dark Romance Paperback Collection - S&D" },
  { name:"Night Fury", sku:"9781958769997", category:"Paperback", basePrice:24.99, productionCost:5.29, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:36.99, freeShipping:0, bookStock:13, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:6, bookInventory:7, bundlesInventory:0, sixMonthBookSales:6, sixMonthBundleSales:0, csvAvgDaily:0.74, csvReorderThreshold:10, leadTime:14, booksInBundle:"", bundles:"The Vampire War Paperback Bundle: Books 1-3,Immortal Book Boyfriends Paperback Bundle,The Complete Dark Romance Paperback Collection" },
  { name:"Night Fury - S&D", sku:"NightFuryS&D", category:"Paperback", basePrice:22.99, productionCost:5.29, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:33.99, freeShipping:0, bookStock:29, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:1, bookInventory:28, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.03, csvReorderThreshold:0, leadTime:14, booksInBundle:"", bundles:"The Vampire War Paperback Bundle: Books 1-3 - S&D,Immortal Book Boyfriends Paperback Bundle - S&D,The Complete Dark Romance Paperback Collection - S&D" },
  { name:"Night Shade", sku:"9780578987439", category:"Paperback", basePrice:22.99, productionCost:4.53, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:36.99, freeShipping:0, bookStock:26, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:6, bookInventory:20, bundlesInventory:0, sixMonthBookSales:6, sixMonthBundleSales:0, csvAvgDaily:0.74, csvReorderThreshold:10, leadTime:14, booksInBundle:"", bundles:"The Vampire War Paperback Bundle: Books 1-3,Immortal Book Boyfriends Paperback Bundle,The Complete Dark Romance Paperback Collection" },
  { name:"Night Shade - S&D", sku:"NightShadeS&D", category:"Paperback", basePrice:20.99, productionCost:4.53, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:33.99, freeShipping:0, bookStock:3, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:1, bookInventory:2, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.03, csvReorderThreshold:0, leadTime:14, booksInBundle:"", bundles:"The Vampire War Paperback Bundle: Books 1-3 - S&D,Immortal Book Boyfriends Paperback Bundle - S&D,The Complete Dark Romance Paperback Collection - S&D" },
  { name:"Spicy Standalone Bundle", sku:"9602009000114", category:"Bundle", basePrice:29.99, productionCost:8.83, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:45.99, freeShipping:0, bookStock:0, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:0, bundlesInventory:8, sixMonthBookSales:0, sixMonthBundleSales:1, csvAvgDaily:0.01, csvReorderThreshold:0, leadTime:14, booksInBundle:"My Brutal Beast,Crowned In Blood", bundles:"" },
  { name:"Spicy Standalone Bundle - S&D", sku:"SpicyStandalonePBUS-S&D", category:"Bundle", basePrice:27.99, productionCost:7.82, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:39.99, freeShipping:0, bookStock:0, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:0, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:2, csvAvgDaily:0.01, csvReorderThreshold:0, leadTime:14, booksInBundle:"My Brutal Beast - S&D,Crowned In Blood - S&D", bundles:"" },
  { name:"The Complete Dark Romance Paperback Collection", sku:"FullStorePBUS", category:"Bundle", basePrice:99.99, productionCost:26.76, shippingCost:2.77, shippingSuppliesCost:4.71, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:122.99, freeShipping:7.00, bookStock:0, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:0, bundlesInventory:4, sixMonthBookSales:0, sixMonthBundleSales:29, csvAvgDaily:0.16, csvReorderThreshold:0, leadTime:14, booksInBundle:"Night Shade,Night Fury,Night Fall,My Brutal Beast,Crowned In Blood Foiled Paperback,Crowned In Blood - Art Pack", bundles:"" },
  { name:"The Complete Dark Romance Paperback Collection - S&D", sku:"TheDarkRomancePBLibraryS&D", category:"Bundle", basePrice:94.99, productionCost:26.76, shippingCost:2.77, shippingSuppliesCost:4.71, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:113.99, freeShipping:7.00, bookStock:0, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:0, bundlesInventory:0, sixMonthBookSales:0, sixMonthBundleSales:3, csvAvgDaily:0.02, csvReorderThreshold:0, leadTime:14, booksInBundle:"Night Shade - S&D,Night Fury - S&D,Night Fall - S&D,My Brutal Beast - S&D,Crowned In Blood - Art Pack,Crowned In Blood Foiled Paperback - S&D", bundles:"" },
  { name:"The Vampire War", sku:"9781958769102", category:"Omnibus", basePrice:49.99, productionCost:11.39, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:69.99, freeShipping:7.00, bookStock:3, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:3, bundlesInventory:0, sixMonthBookSales:1, sixMonthBundleSales:0, csvAvgDaily:0.01, csvReorderThreshold:0, leadTime:14, booksInBundle:"", bundles:"" },
  { name:"The Vampire War - S&D", sku:"TVWOmnibusPBS&D", category:"Omnibus", basePrice:39.99, productionCost:11.39, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:3.00, handlingFeeAddOn:4.50, ttShopPrice:65.99, freeShipping:6.50, bookStock:10, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:10, bundlesInventory:0, sixMonthBookSales:4, sixMonthBundleSales:0, csvAvgDaily:0.02, csvReorderThreshold:0, leadTime:14, booksInBundle:"", bundles:"" },
  { name:"The Vampire War Paperback Bundle: Books 1-3", sku:"9602009000015", category:"Bundle", basePrice:49.99, productionCost:15.70, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:75.99, freeShipping:6.50, bookStock:0, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:0, bundlesInventory:7, sixMonthBookSales:0, sixMonthBundleSales:6, csvAvgDaily:0.03, csvReorderThreshold:0, leadTime:14, booksInBundle:"Night Shade,Night Fury,Night Fall", bundles:"" },
  { name:"The Vampire War Paperback Bundle: Books 1-3 - S&D", sku:"TheVampireWarS&D", category:"Bundle", basePrice:44.99, productionCost:15.70, shippingCost:2.47, shippingSuppliesCost:3.87, paCosts:6.00, handlingFeeAddOn:4.50, ttShopPrice:69.99, freeShipping:7.00, bookStock:0, booksPurchased:0, bundlesPurchased:0, purchasedViaBundles:0, bookInventory:0, bundlesInventory:2, sixMonthBookSales:0, sixMonthBundleSales:0, csvAvgDaily:0.00, csvReorderThreshold:0, leadTime:14, booksInBundle:"Night Shade - S&D,Night Fury - S&D,Night Fall - S&D", bundles:"" }
];

export async function seedDatabaseIfEmpty() {
  const productsRef = collection(db, 'products');
  try {
    const snapshot = await getDocs(productsRef);
    
    if (snapshot.empty) {
      console.log("Seeding database with initial products...");
      const batch = writeBatch(db);
      
      INITIAL_PRODUCTS.forEach((product) => {
        const newDocRef = doc(productsRef);
        batch.set(newDocRef, {
          ...product,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        });
      });
      
      await batch.commit();
      console.log("Database seeded successfully.");
    }
  } catch (error) {
    console.error("Error seeding database:", error);
    handleFirestoreError(error, OperationType.GET, 'products');
  }
}
